name: sentinel2-process
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - gdal
  - fiona
  - rasterio
  - pandas
  - scikit-image
  - geopandas
  - earthpy
  - varname


